name: Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      run_init:
        description: "Run terraform init?"
        required: true
        default: "true"
      run_fmt:
        description: "Run terraform fmt?"
        required: true
        default: "true"
      run_validate:
        description: "Run terraform validate?"
        required: true
        default: "true"
      run_plan:
        description: "Run terraform plan?"
        required: true
        default: "true"

jobs:
  terraform-init:
    if: ${{ github.event.inputs.run_init == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init

  terraform-fmt:
    if: ${{ github.event.inputs.run_fmt == 'true' }}
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check

  terraform-validate:
    if: ${{ github.event.inputs.run_validate == 'true' }}
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform validate

  terraform-plan:
    if: ${{ github.event.inputs.run_plan == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - terraform-fmt
      - terraform-validate
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform plan
